spring.application.name=cdc
server.port=8081

# --- Datasource ---
spring.datasource.url=jdbc:postgresql://localhost:5433/orders
spring.datasource.username=orders_app
spring.datasource.password=orders_app

# --- JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# --- Kafka
spring.kafka.bootstrap-servers=localhost:9092

# --- Actuator ---
management.endpoints.web.exposure.include=health,info,metrics
