spring.application.name=cdc
server.port=8081

# --- Datasource ---
spring.datasource.url=${POSTGRES_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

# --- JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# --- Kafka
spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}

# --- Actuator ---
management.endpoints.web.exposure.include=health,info,metrics
